version: '3.2'

services:
  # mysql:
  #   image: mysql:8.0.16
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: comp_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld
  #   volumes:
  #   - ./docker/mysql/data:/var/lib/mysql
  #   - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #   - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #   - 13306:3306
  postgres:
    image: postgres:11.3
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: postgres
    volumes:
    - ./docker/postgres/data:/var/lib/postgresql/data
    - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - 15432:5432